### ISSUE TITLE
Export cards - PDF or others formats

### ISSUE THREAD

**Issue by glauberramos** [glauberramos/fireideaz#15]

**Comment by eduaquiles** [comment]
Simple workaround is to print the page :)

**Comment by luchillo17** [comment]
I think for pdf it is, however what for others like CSV? it makes sense to have an export & import feat for CSV, like if you want to save a session for future meetings.

**Comment by glauberramos** [comment]
@luchillo17 there is another issue #204 that will cover CSV export

**Comment by luchillo17** [comment]
University & work have me like :sweat: , maybe after i finish this semester.
